# Generated by Django 4.2.7 on 2023-11-13 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='user_id',
            new_name='user',
        ),
    ]
