# Generated by Django 4.2.7 on 2023-11-13 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
        ),
    ]
