# Generated by Django 4.2.7 on 2023-11-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menuitem_average_rating_alter_usercomments_menu_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='rating',
        ),
    ]
