# Generated by Django 4.2.7 on 2023-11-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_rename_item_rating_menu_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='rating',
            field=models.SmallIntegerField(choices=[(1, 'One Star'), (2, 'Two Stars'), (3, 'Three Stars'), (4, 'Four Stars'), (5, 'Five Stars')], default=1),
        ),
    ]
