# Generated by Django 4.2.7 on 2023-11-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
    ]
