# Generated by Django 4.2.7 on 2023-11-21 12:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0017_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='menu_item',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('menu_item', 'user')},
        ),
    ]
