# Generated by Django 4.2.7 on 2023-11-21 12:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0018_rename_item_cart_menu_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='menu_item',
            new_name='object',
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('object', 'user')},
        ),
    ]
