# Generated by Django 4.2.7 on 2023-11-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_category_slug_alter_cart_object_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='restaurant.CartItem', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='object',
        ),
    ]
